/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inteface;

import Main.qltieccuoi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS 10
 */
public class DatTiecCuoi extends javax.swing.JFrame {

     private final String header[] = {"MAKH", "TENCHURE", "TENCODAU", "SODT","NGAY","CA","TIENDATCOC","MASANH","SOLUONGBAN","SOLUONGBANDUTRU"};
    private final DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    public DatTiecCuoi() {
        initComponents();
        loadkh();
    }
    private void loadkh(){
    Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://hotaru:1433;databaseName=QLTIECCUOI;user=sa;password=votinh";
        try {
            conn = DriverManager.getConnection(dbURL);// Câu lệnh xem dữ liệu
            String sql = "select * from KHACHHANG ";// Tạo đối tượng thực thi câu lệnh Select
            st = conn.createStatement();// Thực thi 
            rs = st.executeQuery(sql);
            Vector data = null;
            tblModel.setRowCount(0);
            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không có KH!");
                return;
            }
            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
              data = new Vector();
                data.add(rs.getInt("MAKH"));
                data.add(rs.getString("TENCHURE"));
                data.add(rs.getString("TENCODAU"));
                data.add(rs.getString("SODT"));
                data.add(rs.getString("NGAY"));
                data.add(rs.getString("CA")); 
                data.add(rs.getString("TIENDATCOC"));
                data.add(rs.getString("MASANH"));
                data.add(rs.getString("SOLUONGBAN"));
                data.add(rs.getString("SOLUONGBANDUTRU"));

                // Thêm một dòng vào table model
                tblModel.addRow(data);
            }

            TB1.setModel(tblModel); // Thêm dữ liệu vào table   
            TB1.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
                if(TB1.getSelectedRow()>=0){
                    // jTextFieldbs.setEditable(false);
                    jtmmkh.setText(TB1.getValueAt(TB1.getSelectedRow(),0) + "");
                    jtchure.setText(TB1.getValueAt(TB1.getSelectedRow(),1) + "");
                    jtcodau.setText(TB1.getValueAt(TB1.getSelectedRow(),2) + "");
                    jtsdt.setText(TB1.getValueAt(TB1.getSelectedRow(),3)+ "");
                    //setDate = jDatengay.setDate(TB1.getValueAt(TB1,converUtilDateToSqlDate(),4) + "");
                    jcbca.setSelectedItem(TB1.getValueAt(TB1.getSelectedRow(),5)+ "");
                    jttiendc.setText(TB1.getValueAt(TB1.getSelectedRow(),6) + "");
                    jtloaisanh.setText(TB1.getValueAt(TB1.getSelectedRow(),7) + "");
                    jtslban.setText(TB1.getValueAt(TB1.getSelectedRow(),8) + "");
                    jtslbandutru.setText(TB1.getValueAt(TB1.getSelectedRow(),9) + "");
                    
                    int select = TB1.getSelectedRow();
                    java.util.Date datel = null;
                    try {
                        datel = new SimpleDateFormat("yyyy-MM-dd").parse((String) TB1.getValueAt(select, 4));
                    } catch (ParseException ex) {
                        java.util.logging.Logger.getLogger(DatTiecCuoi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jDatengay.setDate(datel);
                }
            });
            } catch (HeadlessException | SQLException e) {
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param date
     * @return 
     */
    public static java.sql.Date converUtilDateToSqlDate(java.util.Date date){
        if (date != null){
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }
 public static java.util.Date convertSqlDateToUtilDate(java.sql.Date date){
        if(date != null){
            java.util.Date sqlDate = new java.util.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }
 private void search() {
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://hotaru:1433;databaseName=QLTIECCUOI;user=sa;password=votinh";
        try {
            conn = DriverManager.getConnection(dbURL);// Câu lệnh xem dữ liệu
            String sql = "select * from KHACHHANG ";
            if (jtmmkh.getText().length() > 0) {
                sql = sql + " where MAKH = N'" + jtmmkh.getText() + "' or TENCHURE like N'%" + jtmmkh.getText() + "%' or TENCODAU = N'" + jtmmkh.getText() + "'";
            } if(jtmmkh.getText().length()==0){
                 sql = "select * from KHACHHANG ";
            }
            st = conn.createStatement();// Tạo đối tượng thực thi câu lệnh Select
            rs = st.executeQuery(sql);// Thực thi 
            Vector data = null;
            tblModel.setRowCount(0);
            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không Có Khách Hàng Này!");
                return;
            }
            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
              data = new Vector();
                 data.add(rs.getInt("MAKH"));
                data.add(rs.getString("TENCHURE"));
                data.add(rs.getString("TENCODAU"));
                data.add(rs.getString("SODT"));
                data.add(rs.getString("NGAY"));
                data.add(rs.getString("CA")); 
                data.add(rs.getString("TIENDATCOC"));
                data.add(rs.getString("MASANH"));
                data.add(rs.getString("SOLUONGBAN"));
                data.add(rs.getString("SOLUONGBANDUTRU"));
                // Thêm một dòng vào table model
                tblModel.addRow(data);
            }
            TB1.setModel(tblModel); // Thêm dữ liệu vào table
        } catch (HeadlessException | SQLException e) {
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
            }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtchure = new javax.swing.JTextField();
        jtloaisanh = new javax.swing.JTextField();
        jtcodau = new javax.swing.JTextField();
        jttiendc = new javax.swing.JTextField();
        jtsdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDatengay = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtslban = new javax.swing.JTextField();
        jtslbandutru = new javax.swing.JTextField();
        jcbca = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtmmkh = new javax.swing.JTextField();
        jbtlammoi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbttimkiem = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt Tiệc Cưới");

        jPanel1.setLayout(null);

        jLabel2.setText("Điện thoại:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 60, 65, 25);

        jLabel3.setText("Tên Chú Rễ:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 60, 90, 25);

        jLabel6.setText("Ca");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 120, 65, 25);

        jLabel7.setText("Tên cô dâu:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 60, 65, 25);
        jPanel1.add(jtchure);
        jtchure.setBounds(110, 60, 160, 25);

        jtloaisanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtloaisanhActionPerformed(evt);
            }
        });
        jPanel1.add(jtloaisanh);
        jtloaisanh.setBounds(390, 90, 90, 25);

        jtcodau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodauActionPerformed(evt);
            }
        });
        jPanel1.add(jtcodau);
        jtcodau.setBounds(390, 60, 160, 25);
        jPanel1.add(jttiendc);
        jttiendc.setBounds(680, 90, 150, 25);
        jPanel1.add(jtsdt);
        jtsdt.setBounds(680, 60, 150, 25);

        TB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TB1.setToolTipText("");
        TB1.setName(""); // NOI18N
        jScrollPane1.setViewportView(TB1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 870, 200);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Add.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 200, 90, 33);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Erase.png"))); // NOI18N
        jButton2.setText("Xoá");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 200, 90, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Application.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(210, 200, 90, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐẶT TIỆC CƯỚI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 100, 20);

        jLabel4.setText("Ngày");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 65, 25);

        jLabel5.setText("Sảnh");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 90, 65, 25);

        jDatengay.setDate(new java.util.Date(1509012007000L));
        jDatengay.setDateFormatString("MMM d, yyyy");
        jDatengay.setEnabled(false);
        jPanel1.add(jDatengay);
        jDatengay.setBounds(110, 90, 160, 25);

        jLabel8.setText("Tiền Đặt Cọc");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(580, 90, 110, 25);

        jLabel10.setText("Số Lượng Bàn");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 120, 110, 25);

        jLabel11.setText("Số Bàn Dữ Trữ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(580, 120, 100, 25);
        jPanel1.add(jtslban);
        jtslban.setBounds(390, 120, 90, 25);

        jtslbandutru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtslbandutruActionPerformed(evt);
            }
        });
        jPanel1.add(jtslbandutru);
        jtslbandutru.setBounds(680, 120, 150, 25);

        jcbca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn Ca--", "Trưa", "Tối" }));
        jPanel1.add(jcbca);
        jcbca.setBounds(110, 120, 140, 25);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Exit.png"))); // NOI18N
        jButton4.setText("Thát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 200, 90, 33);

        jLabel9.setText("Mã Khách Hàng");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 250, 90, 33);
        jPanel1.add(jtmmkh);
        jtmmkh.setBounds(320, 250, 160, 33);

        jbtlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Refresh.png"))); // NOI18N
        jbtlammoi.setText("Reset");
        jbtlammoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtlammoiMouseClicked(evt);
            }
        });
        jbtlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlammoiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtlammoi);
        jbtlammoi.setBounds(450, 200, 90, 33);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Next.png"))); // NOI18N
        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 200, 90, 33);

        jbttimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Text preview.png"))); // NOI18N
        jbttimkiem.setText("Tìm Kiếm");
        jbttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(jbttimkiem);
        jbttimkiem.setBounds(520, 250, 120, 33);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 40, 840, 2);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 40, 10, 130);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(848, 40, 2, 130);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(10, 172, 840, 2);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(282, 40, 10, 130);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(568, 40, 10, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtslbandutruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtslbandutruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtslbandutruActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://hotaru:1433;databaseName=QLTIECCUOI;user=sa;password=votinh";
        String insert = "INSERT INTO KHACHHANG (TENCHURE,TENCODAU,SODT,NGAY,CA,TIENDATCOC,MASANH,SOLUONGBAN,SOLUONGBANDUTRU) VALUES(?,?,?,?,?,?,?,?,?)";
        try {
            conn = DriverManager.getConnection(dbURL);
            ps = conn.prepareStatement(insert);
            //ps.setString(1, jtmasanh.getText());
            // if (this.jtmasanh.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã Sảnh không thể bỏ trống", "thông báo",2);
            ps.setString(1, jtchure.getText());
            ps.setString(2,jtcodau.getText());//SelectedItem().toString());
        ps.setString(3, jtsdt.getText());
        ps.setDate(4, converUtilDateToSqlDate(jDatengay.getDate()));
        // ps.setString(4,jDatengay.getDateFormatString());
        ps.setString(5,jcbca.getSelectedItem().toString());
        ps.setInt(6,Integer.parseInt(jttiendc.getText()));
        ps.setInt(7,Integer.parseInt(jtloaisanh.getText()));
        ps.setInt(8,Integer.parseInt(jtslban.getText()));
        ps.setInt(9,Integer.parseInt(jtslbandutru.getText()));
        int ret = ps.executeUpdate();
        if (ret != -1) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            this.loadkh();
        }
        else{
            JOptionPane.showMessageDialog(this, "Không Thành Công");
        }      
        } catch (HeadlessException | NumberFormatException | SQLException e) {
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            } catch (SQLException ex2) {
            }   
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtcodauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodauActionPerformed

    private void jtloaisanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtloaisanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtloaisanhActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
          try{
            qltieccuoi pt=new qltieccuoi();
            pt.Updatekh(Integer.parseInt(jtmmkh.getText()),(jtchure.getText()),jtcodau.getText(),Integer.parseInt(jtsdt.getText()),
            converUtilDateToSqlDate(jDatengay.getDate()),(jcbca.getSelectedItem().toString()),Integer.parseInt(jttiendc.getText()),
            Integer.parseInt(jtloaisanh.getText()),Integer.parseInt(jtslban.getText()),
            Integer.parseInt(jtslbandutru.getText()));
            int ret = JOptionPane.showConfirmDialog(this, "Bạn Muốn Sửa?", "Thông Báo", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.YES_OPTION) {
              } else {
                return;
              }
            //pt.Close();
            this.loadkh();
        }catch(ClassNotFoundException | SQLException ex){
            Logger.getLogger(DatTiecCuoi.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
            try{
            qltieccuoi pt=new qltieccuoi();
            pt.deletekh(Integer.parseInt(jtloaisanh.getText()));
            int ret = JOptionPane.showConfirmDialog(this, "Bạn Muốn Xóa ?", "Thông Báo", JOptionPane.YES_NO_OPTION);
            if (ret != JOptionPane.YES_OPTION)
            return;
           // pt.Close();
        }catch(ClassNotFoundException | SQLException ex){
            Logger.getLogger(Nhapsanhc.class.getName()).log(Level.SEVERE,null,ex);
        }
        this.loadkh();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jbtlammoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtlammoiMouseClicked
        // TODO add your handling code here:
        jtmmkh.setText("");
        jtchure.setText("");
        jtcodau.setText("");
        jtloaisanh.setText("");
        jcbca.setSelectedItem("--Chọn Ca--");
        jtsdt.setText("");
       // jDatengay.setDate(d);
        jttiendc.setText("");
        jtslbandutru.setText("");
        jtslban.setText("");
        this.loadkh();
        // tblModel.setRowCount(0);
    }//GEN-LAST:event_jbtlammoiMouseClicked

    private void jbtlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlammoiActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jbtlammoiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DatMonAnDV dm=new DatMonAnDV();
        dm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttimkiemActionPerformed
        // TODO add your handling code here:
        this.search();
    }//GEN-LAST:event_jbttimkiemActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatTiecCuoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DatTiecCuoi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDatengay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbtlammoi;
    private javax.swing.JButton jbttimkiem;
    private javax.swing.JComboBox<String> jcbca;
    private javax.swing.JTextField jtchure;
    private javax.swing.JTextField jtcodau;
    private javax.swing.JTextField jtloaisanh;
    private javax.swing.JTextField jtmmkh;
    private javax.swing.JTextField jtsdt;
    private javax.swing.JTextField jtslban;
    private javax.swing.JTextField jtslbandutru;
    private javax.swing.JTextField jttiendc;
    // End of variables declaration//GEN-END:variables
}
