/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inteface;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Tracuusanh extends javax.swing.JFrame {
private final String header[] = {"MASANH", "TENSANH", "LOAISANH", "SOBANMAX", "GIATIENTOIDA","CHUY"};
    private final DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    /**
     * Creates new form Tracuusanh
     */
    public Tracuusanh() {
        initComponents();
        load();
    }
     private void load(){
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://hotaru:1433;databaseName=QLTIECCUOI;user=sa;password=votinh";
        try {
            conn = DriverManager.getConnection(dbURL);// Câu lệnh xem dữ liệu
            String sql = "select * from SANH ";// Tạo đối tượng thực thi câu lệnh Select
            st = conn.createStatement();// Thực thi 
            rs = st.executeQuery(sql);
            Vector data = null;
            tblModel.setRowCount(0);
            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không Có Sảnh Này!");
                return;
            }
            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
              data = new Vector();
                data.add(rs.getString("MASANH"));
                data.add(rs.getString("TENSANH"));
                data.add(rs.getString("LOAISANH"));
                data.add(rs.getString("SOBANMAX"));
                data.add(rs.getString("GIATIENTOIDA"));
                data.add(rs.getString("CHUY"));
                // Thêm một dòng vào table model
                tblModel.addRow(data);
            }
            tbsp.setModel(tblModel); // Thêm dữ liệu vào table
        } catch (HeadlessException | SQLException e) {
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
            }
        }
    }
 
private void search() {
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://hotaru:1433;databaseName=QLTIECCUOI;user=sa;password=votinh";
        try {
            conn = DriverManager.getConnection(dbURL);// Câu lệnh xem dữ liệu
            String sql = "select * from SANH ";
            if (jtracuu.getText().length() > 0) {
                sql = sql + " where MASANH = N'" + jtracuu.getText() + "' or TENSANH like N'%" + jtracuu.getText() + "%' or LOAISANH = N'" + jtracuu.getText() + "'";
            } if(jtracuu.getText().length()==0){
                 sql = "select * from SANH ";
            }
            st = conn.createStatement();// Tạo đối tượng thực thi câu lệnh Select
            rs = st.executeQuery(sql);// Thực thi 
            Vector data = null;
            tblModel.setRowCount(0);
            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không Có Sảnh Này!");
                return;
            }
            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
              data = new Vector();
                data.add(rs.getString("MASANH"));
                data.add(rs.getString("TENSANH"));
                data.add(rs.getString("LOAISANH"));
                data.add(rs.getString("SOBANMAX"));
                data.add(rs.getString("GIATIENTOIDA"));
                data.add(rs.getString("CHUY"));
                // Thêm một dòng vào table model
                tblModel.addRow(data);
            }
            tbsp.setModel(tblModel); // Thêm dữ liệu vào table
        } catch (HeadlessException | SQLException e) {
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtracuu = new javax.swing.JTextField();
        jbttimkiem = new javax.swing.JButton();
        jbtthoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbsp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRA CỨU SẢNH");

        jPanel1.setLayout(null);

        jtracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtracuuActionPerformed(evt);
            }
        });
        jPanel1.add(jtracuu);
        jtracuu.setBounds(140, 70, 310, 40);

        jbttimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Text preview.png"))); // NOI18N
        jbttimkiem.setText("Tìm Kiếm");
        jbttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(jbttimkiem);
        jbttimkiem.setBounds(500, 70, 110, 40);

        jbtthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Exit.png"))); // NOI18N
        jbtthoat.setText("Thoát");
        jbtthoat.setPreferredSize(new java.awt.Dimension(101, 33));
        jbtthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtthoatActionPerformed(evt);
            }
        });
        jPanel1.add(jbtthoat);
        jbtthoat.setBounds(500, 120, 110, 40);

        jScrollPane2.setViewportView(tbsp);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 180, 700, 280);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TRA CỨU SẢNH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/hinh-nen-hinh-anh-dep-ve-sach-30.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtracuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtracuuActionPerformed

    private void jbttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttimkiemActionPerformed
        // TODO add your handling code here:
        this.search();
    }//GEN-LAST:event_jbttimkiemActionPerformed

    private void jbtthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtthoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbtthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tracuusanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tracuusanh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtthoat;
    private javax.swing.JButton jbttimkiem;
    private javax.swing.JTextField jtracuu;
    private javax.swing.JTable tbsp;
    // End of variables declaration//GEN-END:variables
}
