/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.Login;
import inteface.About;
import inteface.Baocaodoanhsoc;
import inteface.Nhapsanhc;
import inteface.DatTiecCuoi;
import inteface.DatMonAnDV;
import inteface.Tracuusanh;
import inteface.TraCuuTiecC;
import inteface.HoaDonThanhToan;

/**
 *
 * @author DELL
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanaa = new javax.swing.JPanel();
        Jpana = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        miNhapThongTinKhach = new javax.swing.JMenuItem();
        miTraCuuTiec = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miQuanlyHoaDon = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        miBaoCaoDoanhSo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TIỆC CƯỚI");

        Jpanaa.setPreferredSize(new java.awt.Dimension(1170, 658));
        Jpanaa.setLayout(null);

        Jpana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/05_KLK Photography_Ritz Carlton 2016.jpg"))); // NOI18N
        Jpana.setPreferredSize(new java.awt.Dimension(1366, 768));
        Jpanaa.add(Jpana);
        Jpana.setBounds(0, 0, 1500, 760);

        menuBar.setPreferredSize(new java.awt.Dimension(413, 25));

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Home.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Quản Lý Sảnh");
        fileMenu.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Notes.png"))); // NOI18N
        jMenuItem4.setText("Nhập Sảnh");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Text preview.png"))); // NOI18N
        jMenuItem5.setText("Tra Cứu Sảnh");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem5);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/People.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Đặt Tiệc Cưới");
        editMenu.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        miNhapThongTinKhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Notes.png"))); // NOI18N
        miNhapThongTinKhach.setMnemonic('t');
        miNhapThongTinKhach.setText("Nhập Thông Tin  Tiệc Cưới");
        miNhapThongTinKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNhapThongTinKhachActionPerformed(evt);
            }
        });
        editMenu.add(miNhapThongTinKhach);

        miTraCuuTiec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Modify.png"))); // NOI18N
        miTraCuuTiec.setMnemonic('y');
        miTraCuuTiec.setText("Nhập Thông Tin MA/DV");
        miTraCuuTiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTraCuuTiecActionPerformed(evt);
            }
        });
        editMenu.add(miTraCuuTiec);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Text preview.png"))); // NOI18N
        jMenuItem6.setText("Tra Cứu Khách Hàng");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem6);

        menuBar.add(editMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Report.png"))); // NOI18N
        jMenu1.setText("Quản lý Hoá Đơn");

        miQuanlyHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Print.png"))); // NOI18N
        miQuanlyHoaDon.setMnemonic('c');
        miQuanlyHoaDon.setText("Truy Xuất Hóa Đơn");
        miQuanlyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuanlyHoaDonActionPerformed(evt);
            }
        });
        jMenu1.add(miQuanlyHoaDon);

        menuBar.add(jMenu1);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Database.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Báo Cáo");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });

        miBaoCaoDoanhSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Report.png"))); // NOI18N
        miBaoCaoDoanhSo.setMnemonic('a');
        miBaoCaoDoanhSo.setText("Báo cáo doanh số");
        miBaoCaoDoanhSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBaoCaoDoanhSoActionPerformed(evt);
            }
        });
        helpMenu.add(miBaoCaoDoanhSo);

        menuBar.add(helpMenu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Help book.png"))); // NOI18N
        jMenu2.setText("Help");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Info.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Lock.png"))); // NOI18N
        jMenuItem3.setText("Đăng Nhập");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNhapThongTinKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNhapThongTinKhachActionPerformed
        DatTiecCuoi TTkhach = new DatTiecCuoi();
        TTkhach.setVisible(true);
    }//GEN-LAST:event_miNhapThongTinKhachActionPerformed

    private void miTraCuuTiecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTraCuuTiecActionPerformed
        DatMonAnDV dm=new DatMonAnDV();
        dm.setVisible(true);
    }//GEN-LAST:event_miTraCuuTiecActionPerformed

    private void miQuanlyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuanlyHoaDonActionPerformed
            HoaDonThanhToan hd=new HoaDonThanhToan();
            hd.setVisible(true);
    }//GEN-LAST:event_miQuanlyHoaDonActionPerformed

    private void miBaoCaoDoanhSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBaoCaoDoanhSoActionPerformed
        Baocaodoanhsoc DS = new Baocaodoanhsoc();
        DS.setVisible(true);
        //Jpana.add(DS);
    }//GEN-LAST:event_miBaoCaoDoanhSoActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        About tt = new About();
        tt.setVisible(true);
        Jpana.add(tt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Login in= new Login();
        this.setVisible(false);
        in.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
               Nhapsanhc nsanh = new Nhapsanhc();
        nsanh.setVisible(true);
        //Jpana.add(nsanh);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
               Tracuusanh nh = new Tracuusanh();
        nh.setVisible(true);
       // Jpana.add(nh);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TraCuuTiecC tc=new TraCuuTiecC();
        tc.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jpana;
    private javax.swing.JPanel Jpanaa;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miBaoCaoDoanhSo;
    private javax.swing.JMenuItem miNhapThongTinKhach;
    private javax.swing.JMenuItem miQuanlyHoaDon;
    private javax.swing.JMenuItem miTraCuuTiec;
    // End of variables declaration//GEN-END:variables

}