/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.GiaoDien;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JInternalFrame();
        bLogin = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        pfPassword = new javax.swing.JPasswordField();
        chbRemmerber = new javax.swing.JCheckBox();
        iMessge = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 572));
        getContentPane().setLayout(null);

        Login.setClosable(true);
        Login.setTitle("Thông Tin Đăng Nhập");
        Login.setToolTipText("");
        Login.setVisible(true);

        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Go forward.png"))); // NOI18N
        bLogin.setText("Login");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Refresh.png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        chbRemmerber.setText("Remmerber");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/People.png"))); // NOI18N
        jLabel1.setText("UserName :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/24x24/Lock.png"))); // NOI18N
        jLabel2.setText("PassWord :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("ĐĂNG NHẬP");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(chbRemmerber)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bReset))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfPassword)
                                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(iMessge, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbRemmerber)
                .addGap(33, 33, 33)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin)
                    .addComponent(bReset))
                .addGap(18, 18, 18)
                .addComponent(iMessge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Login);
        Login.setBounds(240, 120, 348, 310);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/chim-bo-cau-2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -40, 840, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        if(tfUsername.getText().equalsIgnoreCase("hiếu")&& pfPassword.getText().equals("votinh"))
                  {
            if(chbRemmerber.isSelected()){
                iMessge.setText("Đăng Nhập Thành Công !");
            }else{
                iMessge.setText("Dăng Nhập Thành Công !");
            }
            GiaoDien main= new GiaoDien();
            this.setVisible(false);
            main.setVisible(true);
        }else{
            iMessge.setText("Đăng Thất Bại,Sai Mật Khẩu Hoặc...");
        }
        if(tfUsername.getText().equalsIgnoreCase("hoàng khang")&& pfPassword.getText().equals("votinh"))
                  {
            if(chbRemmerber.isSelected()){
                iMessge.setText("Đăng Nhập Thành Công !");
            }else{
                iMessge.setText("Dăng Nhập Thành Công !");
            }
           GiaoDien main= new GiaoDien();
            this.setVisible(false);
            main.setVisible(true);
        }else{
            iMessge.setText("Đăng Thất Bại,Sai Mật Khẩu Hoặc...");
        }
        if(tfUsername.getText().equalsIgnoreCase("đạt")&& pfPassword.getText().equals("votinh"))
                  {
            if(chbRemmerber.isSelected()){
                iMessge.setText("Đăng Nhập Thành Công !");
            }else{
                iMessge.setText("Dăng Nhập Thành Công !");
            }
       GiaoDien main= new GiaoDien();
            this.setVisible(false);
            main.setVisible(true);
        }else{
            iMessge.setText("Đăng Thất Bại,Sai Mật Khẩu Hoặc...");
        }
        if(tfUsername.getText().equalsIgnoreCase("minh khang")&& pfPassword.getText().equals("votinh"))
        {
            if(chbRemmerber.isSelected()){
                iMessge.setText("Đăng Nhập Thành Công !");
            }else{
                iMessge.setText("Dăng Nhập Thành Công !");
            }
           GiaoDien main= new GiaoDien();
            this.setVisible(false);
            main.setVisible(true);
        }else{
            iMessge.setText("Đăng Thất Bại,Sai Mật Khẩu Hoặc...");
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        tfUsername.setText("");
        pfPassword.setText("");
        iMessge.setText("");
        chbRemmerber.setSelected(false);
    }//GEN-LAST:event_bResetActionPerformed

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        // TODO add your handling code here;
    }//GEN-LAST:event_bLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Login;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bReset;
    private javax.swing.JCheckBox chbRemmerber;
    private javax.swing.JLabel iMessge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
/*select EncryotedData=EncryptByPassPhrase('hieu','234567')*/